version: "3.7"

services:
    chat-mongodb:
        image: mongo:4.4.4
        container_name: chat-mongodb
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - chat-mongo-volume:/data/db

    chat-mysql-db:
        image: mysql:latest
        container_name: chat-mysql-db
        ports:
            - "3307:3306"
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        command:
            - --character-set-server=utf8mb4
        volumes:
            - mysql-volume:/var/lib/mysql

    chat-redis:
        image: redis:6.0.5
        container_name: chat-redis
        ports:
            - "6378:6379"
        restart: always
        entrypoint:
            - "redis-server"
            - "--notify-keyspace-events AKE"

    server:
        build:
            context: ./server
            target: development
        container_name: server
        ports:
            - "4003:4003"
        restart: always
        depends_on:
            - chat-redis
            - chat-mongodb
            - chat-mysql-db
        volumes:
            - ./server/src:/app/src
        env_file:
            - .env
        environment:
            - SYNC_DATA

volumes:
    chat-mongo-volume:
    mysql-volume:
